spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: 'mongodb://user:passw@localhost:27017/vtv?authSource=admin'
      #Deberían ser dos bases independientes, por temas practicos cree una sola llamada 'vtv'
      auto-index-creation: true


server:
  port: 8081
