spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  data:
    mongodb:
      uri: 'mongodb://root:example@localhost:27017/vtv?authSource=admin' #'mongodb://user:passw@localhost:27017/vtv?authSource=admin'
      auto-index-creation: true

publisher:
  inspection:
    queue:
      name: 'cola1'


appointments:
  months-enable:
    - FEBRUARY
    - MARCH
    - APRIL
    - MAY
    - OCTOBER
    - NOVEMBER
    - DECEMBER
  days-enable:
    - TUESDAY
    - WEDNESDAY
    - FRIDAY
  hours-enable:
    - 9
    - 14
    - 15
    - 16
    - 17
  from-hour: 9
  to-hour: 18
  per-hour: 3
  holiday-days:
    - '2023-10-21'


#TODO: Dias, lunes martes, etc tiene que ser una lista

server:
  port: 9820
